### ISSUE TITLE
multiple template switching oligos?

### ISSUE THREAD

**Issue by onecarbon** [z0on/tag-based_RNAseq#2]
Hi 

Thanks for this - I am interested in trying it out! Could you clarify the reason for the multiple template switching oligos in this version of the protocol? It looks like the published versions have only one? Are all three now recommended?

Thanks

**Comment by z0on** [comment]
Hello! Three oligos are needed to diversify base composition near beginning of the read, which is very important for latest models of illumina sequencers.

iPhone. Apologies for brevity

**Comment by onecarbon** [comment]
Thanks! will try that way then
